### PR TITLE
SkinDownloader v2

### PR DESCRIPTION
**Pull request by DanielmGM**
New features, check the post in the forum

### CODE REVIEW

**Comment by ThaMattie** [comment]
Aurora only supports integer version numbers. Also, if you do not change the version number, it will not show an update message in repo browser. Please make it version 2 or something

**Comment by DanielmGM** [comment]
It works, the script has an automatic update checker in the hosting, the olny thing is that it doesnt ahow the .1 in the scripts list, but it doesnt matter

**Comment by ThaMattie** [comment]
I know it runs, but repobrowser will not get the new source unless you change the number, it has a caching mechanism. If you leave the number, people will download the old version and need to update right away. I will not approve the pull request with this version number.

**Comment by DanielmGM** [comment]
Done!

**Comment by ThaMattie** [comment]
there is something wrong with your linebreaks. it messes everything up in the repo browser

**Comment by DanielmGM** [comment]
It's charset is UTF8 without BOM, may be that?

**Comment by ThaMattie** [comment]
I don't know. the previous version was fine. You can check here on git, everything is on 1 line

**Comment by DanielmGM** [comment]
Yes, but it works, how's that aurorarepo cant read it? If it reads line by line for the "metadata" like the scriptTitle then i'll gonna put the metadata in single lines if you want

**Pull request merged**
