### PR TITLE
Add XefuSpoofer by Derf

### PR DESCRIPTION
**Pull request by DerfJagged**
This script will allow a user to select a specific Xenon Fusion (xefu) file to use as the original Xbox emulator. It backs up the existing xefu files to another directory and also gives the user an option to restore their xefu files to default.

### CODE REVIEW

**Comment by Swizzy** [comment]
It's ok to commit changes to a existing PR, and you should probably avoid using he same exact message for when you update things - it's far better in general to briefly explain what changed and/or why

**Comment by DerfJagged** [comment]
Got it. Just updated a string in that commit. No further changes planned.

**Comment by DerfJagged** [comment]
Could you add it to the XboxUnity backend?

**Comment by DerfJagged** [comment]
Could you add it to the XboxUnity backend so it shows up in the Aurora repo on 360 @Swizzy?

**Comment by Swizzy** [comment]
> Could you add it to the XboxUnity backend so it shows up in the Aurora repo on 360 @Swizzy?

Sorry about late reply - unfortunately, i cannot - i don't have server access, this is however supposed to be automated, something that is done once per day from what i remember. I've asked those with access to the server to look into it

**Comment by Ste1io** [comment]
@DerfJagged I'll need to do some digging still to sort out the script for handling this, but for the meantime I packed up the script and pushed it to the server along with the adding it to the other utility script listings.

Please confirm if you're able to install it through Aurora.

**Comment by DerfJagged** [comment]
Yes, I am able to. Thanks!

**Pull request merged**
